language: node_js
node_js:
    - "stable"
cache:
  directories:
    - node_modules
before_install:
    - npm update
install:
    - npm install
script:
    - CI=true npm test
    - npm run build
after_success:
    - curl -X POST -d {} https://api.netlify.com/build_hooks/5d5637291af2ec337b7a8fad
branches:
    only:
        - master
